feat: Add AuthenticationFlowBindingOverrides to Keycloak Client
epam/edp-keycloak-operator pull request #118
Opened 2024-12-20 15:42 UTC by dougkirkley

# Pull Request Template

## Description
I needed the ability to use a client specific setup for browser and direct grant flows. This allows overriding those two auth flows on a client basis.

Fixes #116 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Enhancement (non-breaking change which improves an existing feature or documentation)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

## How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Pull Request contains one commit. I squash my commits.

2024-12-23 13:18 UTC, zmotso commented
/recheck

2024-12-23 14:43 UTC, zmotso requested changes
@dougkirkley Thank you for contribution.
Please fix a couple of comments, and we will merge your PR.

2024-12-23 14:43 UTC, zmotso commented on api/v1/keycloakclient_types.go
> +	AuthenticationFlowBindingOverrides AuthenticationFlowBindingOverrides `json:"authenticationFlowBindingOverrides,omitempty"`
Let's make it a pointer `AuthenticationFlowBindingOverrides *AuthenticationFlowBindingOverrides.`
Because, in your case, the empty value is still present on the CR.
```
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: keycloakclient-sample
  namespace: default
spec:
  authenticationFlowBindingOverrides: {}
  ...
  ```

2024-12-23 14:43 UTC, zmotso commented on config/samples/v1_v1_keycloakclient.yaml
> +    direct_grant: "direct grant"
directGrant

2024-12-23 14:43 UTC, zmotso commented on controllers/keycloakclient/chain/put_client.go
> +		keycloakClient.Spec.AuthenticationFlowBindingOverrides = *authFlows
If we generate a new secret in the method `secret, err:= el.getSecret(ctx, keycloakClient)` and then update the keycloakClient CR, we will rewrite the original values `keycloakClient.Spec.AuthenticationFlowBindingOverrides`.

I suggest modifying the function `ConvertSpecToClient (spec *keycloakApi.KeycloakClientSpec, clientSecret, realmName string, authFlowOverride map[string]string)` and passing these values directly.

2024-12-23 14:43 UTC, zmotso commented on api/v1/keycloakclient_types.go
>  }
Add this field to the tests `keycloakclient_controller_integration_test.go`
```
By("Creating a KeycloakClient")
		keycloakClient := &keycloakApi.KeycloakClient{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "test-keycloak-client-with-secret-ref",
				Namespace: ns,
			},
			Spec: keycloakApi.KeycloakClientSpec{
			...
			AuthenticationFlowBindingOverrides ...
```

2024-12-24 09:25 UTC, zmotso commented
@SergK  We can merge this PR.

2024-12-24 09:58 UTC, SergK approved these changes
@dougkirkley thank you for the contribution.
@zmotso thanks for the review

2024-12-24 09:59 UTC, merged